In [ ]:
import numpy as np
from sklearn.decomposition import PCA

# Generate sample data
np.random.seed(0)
X = np.random.randn(100, 3)  # 100 samples, 3 features
X = X - X.mean(axis=0)       # Center the data

# Compute PCA using covariance matrix
pca = PCA()
Y = pca.fit_transform(X)     # PC scores

# Check correlation between PC scores
correlation_matrix = np.corrcoef(Y, rowvar=False)
print("Correlation matrix of PC scores:\n", correlation_matrix)

# Verify off-diagonal entries are near zero
assert np.allclose(np.diag(np.diag(correlation_matrix)), correlation_matrix, atol=1e-10)
print("\nAll off-diagonal correlations are effectively zero!")

Correlation matrix of PC scores:
 [[ 1.00000000e+00 -8.35165202e-17  1.64908742e-16]
 [-8.35165202e-17  1.00000000e+00 -8.66421120e-17]
 [ 1.64908742e-16 -8.66421120e-17  1.00000000e+00]]

All off-diagonal correlations are effectively zero!
